name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - test-cicd  
      - main      
  pull_request:
    branches:
      - main       
jobs:
  # Job 1: build và test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install -U pytest
          pytest 
          pytest/tests
      - name: Run flake8 linting
        run: |
          pip install flake8
          flake8 .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      - name: Build Docker image
        run: |
          docker build -t myapp .
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

  # Job 2: Deploy
  deploy:
    needs: build_and_test 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Chỉ deploy khi có push vào nhánh main

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}         # Địa chỉ IP hoặc hostname của server
          username: ${{ secrets.SERVER_USER }}     # Tên người dùng SSH trên server
          key: ${{ secrets.SSH_PRIVATE_KEY }}      # SSH private key để đăng nhập vào server
          script: |
            # Pull image vừa được push lên DockerHub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

            # Dừng và xóa container cũ (nếu có)
            docker stop myapp-container || true  # Dừng container nếu nó đang chạy
            docker rm myapp-container || true    # Xóa container cũ

            # Chạy container mới với image đã pull về
            docker run -d -p 80:80 --name myapp-container ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
