name: WEB CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build backend Docker image
      run: |
        docker build -t phuowngvo/backend:latest ./WEB/backend

    - name: Push backend Docker image
      run: |
        docker push phuowngvo/backend:latest

    - name: Build frontend Docker image
      run: |
        docker build -t phuowngvo/frontend:latest ./WEB/frontend

    - name: Push frontend Docker image
      run: |
        docker push phuowngvo/frontend:latest
